from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, Field


class BANTScore(BaseModel):
    """Structured BANT scoring output for a single lead."""

    lead_name: str = Field(description="Full name of the lead")
    
    # Quantitative category scores (0 to 25 each, summing to 100 total)
    budget_score: int = Field(
        ge=0, le=25, default=0,
        description="Budget dimension score from 0-25 based on financial signals and capacity"
    )
    authority_score: int = Field(
        ge=0, le=25, default=0,
        description="Authority dimension score from 0-25 based on decision-maker role and sign-off status"
    )
    need_score: int = Field(
        ge=0, le=25, default=0,
        description="Need dimension score from 0-25 based on urgency, pain points, and product fit"
    )
    timeline_score: int = Field(
        ge=0, le=25, default=0,
        description="Timeline dimension score from 0-25 based on purchase horizon and urgency"
    )
    
    # Qualitative category signals
    budget_signal: str = Field(
        description="What the notes suggest about budget/spending capacity, "
        "or 'not mentioned' if there is no evidence either way"
    )
    authority_signal: str = Field(
        description="What the notes/job title suggest about the lead's "
        "decision-making authority"
    )
    need_signal: str = Field(
        description="What the notes suggest about the lead's need or pain point"
    )
    timeline_signal: str = Field(
        description="What the notes suggest about urgency/timeline, "
        "or 'not mentioned' if there is no evidence either way"
    )
    
    # Overall score and qualification
    bant_score: int = Field(
        ge=0, le=100, description="Overall BANT score from 0-100 (sum of B + A + N + T)"
    )
    qualification: Literal["Qualified", "Unqualified"] = Field(
        description="Final qualification label based on bant_score and threshold"
    )
    rationale: str = Field(
        description="1-2 sentence explanation citing the specific evidence used from the lead record"
    )
    key_pain_points: List[str] = Field(
        default_factory=list,
        description="Key business pain points or requirements identified"
    )
    recommended_action: str = Field(
        default="Standard follow-up",
        description="Recommended sales action (e.g. Schedule discovery call, Send product catalog, Nurture for Q4)"
    )


class EmailResponse(BaseModel):
    """Structured email generated by Agent 2 for outreach or nurturing."""

    lead_name: str = Field(description="Full name of recipient")
    recipient_email: str = Field(description="Target email address")
    email_type: Literal["sales_pitch", "nurturing_followup"] = Field(
        description="'sales_pitch' for Qualified leads, 'nurturing_followup' for Unqualified leads"
    )
    subject: str = Field(description="Engaging, personalized email subject line")
    body: str = Field(
        description="Full email body text with salutation, personalized content, value propositions, and sign-off"
    )
    call_to_action: str = Field(
        description="Clear, low-friction next step (e.g. 15-minute intro call, review sample kit)"
    )
    talking_points: List[str] = Field(
        default_factory=list,
        description="Key value propositions or points referenced in the email"
    )


class LeadProcessingResult(BaseModel):
    """Full end-to-end processing result combining lead, score, and email response."""

    lead_data: Dict[str, Any] = Field(description="Original input lead record")
    bant_score: BANTScore = Field(description="BANT qualification assessment")
    email_response: Optional[EmailResponse] = Field(
        default=None, description="Generated email draft"
    )
    email_delivery_status: Literal["draft", "sent", "simulated", "failed", "pending"] = Field(
        default="draft", description="Current status of email delivery"
    )
    email_sent_at: Optional[str] = Field(
        default=None, description="ISO timestamp when email was transmitted/simulated"
    )
    delivery_notes: Optional[str] = Field(
        default=None, description="Notes or error details from email delivery service"
    )
