from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, Field


class BANTScore(BaseModel):
    """Structured BANT scoring output for a single lead."""

    lead_name: str = Field(description="Full name of the lead")

    budget_score: int = Field(
        ge=0, le=25, default=0,
        description="Budget dimension score from 0-25 based on financial signals and capacity"
    )
    authority_score: int = Field(
        ge=0, le=25, default=0,
        description="Authority dimension score from 0-25 based on decision-maker role and sign-off status"
    )
    need_score: int = Field(
        ge=0, le=25, default=0,
        description="Need dimension score from 0-25 based on urgency, pain points, and product fit"
    )
    timeline_score: int = Field(
        ge=0, le=25, default=0,
        description="Timeline dimension score from 0-25 based on purchase horizon and urgency"
    )

    budget_signal: str = Field(
        description="What the notes suggest about budget/spending capacity, "
        "or 'not mentioned' if there is no evidence either way"
    )
    authority_signal: str = Field(
        description="What the notes/job title suggest about the lead's "
        "decision-making authority"
    )
    need_signal: str = Field(
        description="What the notes suggest about the lead's need or pain point"
    )
    timeline_signal: str = Field(
        description="What the notes suggest about urgency/timeline, "
        "or 'not mentioned' if there is no evidence either way"
    )

    bant_score: int = Field(
        ge=0, le=100, description="Overall BANT score from 0-100 (sum of B + A + N + T)"
    )
    qualification: Literal["Qualified", "Unqualified"] = Field(
        description="Final qualification label based on bant_score and threshold"
    )
    rationale: str = Field(
        description="1-2 sentence explanation citing the specific evidence used from the lead record"
    )
    key_pain_points: List[str] = Field(
        default_factory=list,
        description="Key business pain points or requirements identified"
    )
    recommended_action: str = Field(
        default="Standard follow-up",
        description="Recommended sales action (e.g. Schedule discovery call, Send product catalog, Nurture for Q4)"
    )


class EmailResponse(BaseModel):
    """Structured email generated by Agent 2 for outreach or nurturing."""

    lead_name: str = Field(description="Full name of recipient")
    recipient_email: str = Field(description="Target email address")
    email_type: Literal["sales_pitch", "nurturing_followup"] = Field(
        description="'sales_pitch' for Qualified leads, 'nurturing_followup' for Unqualified leads"
    )
    subject: str = Field(description="Engaging, personalized email subject line")
    body: str = Field(
        description="Full email body text with salutation, personalized content, value propositions, and sign-off"
    )
    call_to_action: str = Field(
        description="Clear, low-friction next step (e.g. 15-minute intro call, review sample kit)"
    )
    talking_points: List[str] = Field(
        default_factory=list,
        description="Key value propositions or points referenced in the email"
    )


class EmailValidationResult(BaseModel):
    """Result of the fact-checker validating generated email content."""

    status: Literal["PASS", "FAIL", "SKIPPED"] = Field(default="SKIPPED")
    is_valid: bool = Field(default=True)
    issues: List[str] = Field(default_factory=list)
    evidence: str = Field(default="No unsupported claims detected.")
    claim: Optional[str] = Field(default=None)
    retry_count: int = Field(default=0)
    max_retries: int = Field(default=2)


class LeadClassification(BaseModel):
    """Email classification before BANT evaluation."""

    classification: Literal["SPAM", "NON_SALES", "GENUINE_LEAD"]
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str


class LeadIntent(BaseModel):
    """Customer intent for genuine sales leads."""

    intent: Literal[
        "PRODUCT_INQUIRY",
        "PRICING_INQUIRY",
        "DEMO_REQUEST",
        "PURCHASE_INTENT",
        "INFORMATION_REQUEST",
        "FOLLOW_UP",
        "GENERAL_INQUIRY",
        "UNKNOWN",
    ]
    confidence: float = Field(ge=0.0, le=1.0)
    evidence: str


class LeadSentiment(BaseModel):
    """Customer sentiment signal only."""

    sentiment: Literal["POSITIVE", "NEUTRAL", "NEGATIVE"]
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str


class NextBestAction(BaseModel):
    """Recommended next action for sales team."""

    action: str
    reason: str
    priority: Literal["HIGH", "MEDIUM", "LOW"]


class LeadProcessingResult(BaseModel):
    """Full end-to-end processing result combining lead, score, and email response."""

    lead_data: Dict[str, Any] = Field(description="Original input lead record")
    bant_score: BANTScore = Field(description="BANT qualification assessment")
    classification: Optional[LeadClassification] = Field(default=None, description="Spam / non-sale / lead classification")
    intent: Optional[LeadIntent] = Field(default=None, description="Customer intent for genuine sales leads")
    sentiment: Optional[LeadSentiment] = Field(default=None, description="Customer tone signal")
    next_best_action: Optional[NextBestAction] = Field(default=None, description="Recommended action for the salesperson")
    email_response: Optional[EmailResponse] = Field(default=None, description="Generated email draft")
    email_validation: Optional[EmailValidationResult] = Field(default=None, description="Email hallucination validation result")
    email_delivery_status: Literal["draft", "sent", "simulated", "failed", "pending", "skipped"] = Field(
        default="draft", description="Current status of email delivery"
    )
    email_sent_at: Optional[str] = Field(default=None, description="ISO timestamp when email was transmitted/simulated")
    delivery_notes: Optional[str] = Field(default=None, description="Notes or error details from email delivery service")
    lead_history: List[Dict[str, Any]] = Field(default_factory=list, description="Historical lead interactions")
    bant_history: List[Dict[str, Any]] = Field(default_factory=list, description="Historical BANT score evolution")

    model_config = {"extra": "ignore"}
